### ISSUE TITLE
404 (410) from different domain breaks all further writeCapture-calls

### ISSUE THREAD

**Issue by bpletzer** [iamnoah/writeCapture#22] opened 2011-04-05 13:50 UTC
Hi, 

great functionality so far!

It seems, that 404 (410) from different domains seem to break all further writeCapture-calls.

Try injecting: '<scr'+'ipt type="text/javascript" src="http://www.google.de/muhkuh/rofl.js"></scr'+'ipt>'

greetings

Benedikt

**Comment by iamnoah** [comment] 2011-04-05 14:49
Can you include a full script/test case?

For a single call to capture, the assumption is that any scripts in the same html fragment are interdependent.

**Comment by bpletzer** [comment] 2011-04-05 16:41
sure, you can find an example here: https://gist.github.com/903966

try changing the url of one to local /error/404.js (and let it thow an 404) and it will work

**Comment by bpletzer** [comment] 2011-04-11 07:09
Could you reprdouce the problem?

**Comment by iamnoah** [comment] 2011-04-11 13:41
Ah, so the issue is cross domain scripts that fail to load. This is a sticky problem. The only way to load a XDomain script is via script tag injection, which doesn't have a simple way to determine failure, so we don't know if the script finished loading.

**Comment by iamnoah** [comment] 2011-08-12 01:17
Closing on the assumption this was worked around.

**Closed as completed by iamnoah** 2011-08-12 01:18 UTC
